package com.itheima;

import com.itheima.bos.domain.NoticeBill;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.itheima.com/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllNotAssociation", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindAllNotAssociation")
    @ResponseWrapper(localName = "findAllNotAssociationResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindAllNotAssociationResponse")
    public List<Customer> findAllNotAssociation();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itheima.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<Integer> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedzoneIdByAddress", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindDecidedzoneIdByAddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByAddressResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindDecidedzoneIdByAddressResponse")
    public String findDecidedzoneIdByAddress(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllHasAssociation", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindAllHasAssociation")
    @ResponseWrapper(localName = "findAllHasAssociationResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindAllHasAssociationResponse")
    public List<Customer> findAllHasAssociation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
